export default {
    "exts": [
        "txt",
        "log",
        "coffee",
        "kode",
        "js",
        "ts",
        "swift",
        "json",
        "noon",
        "yml",
        "yaml",
        "cpp",
        "hpp",
        "cxx",
        "mm",
        "c",
        "h",
        "cs",
        "frag",
        "vert",
        "html",
        "htm",
        "pug",
        "md",
        "styl",
        "css",
        "scss",
        "sass",
        "svg",
        "plist",
        "py",
        "sh",
        "bash",
        "fish",
        "iss",
        "ini"
    ],
    "lang": {
        "coffee": {
            "if": "keyword",
            "then": "keyword",
            "else": "keyword",
            "do": "keyword",
            "for": "keyword",
            "while": "keyword",
            "new": "keyword",
            "try": "keyword",
            "catch": "keyword",
            "throw": "keyword",
            "class": "keyword",
            "super": "keyword",
            "return": "keyword",
            "switch": "keyword",
            "break": "keyword",
            "continue": "keyword",
            "true": "keyword",
            "typeof": "keyword",
            "extends": "keyword",
            "instanceof": "keyword",
            "__dirname": "keyword",
            "__filename": "keyword",
            "Infinity": "keyword",
            "args": "module",
            "childp": "module",
            "console": "module",
            "document": "module",
            "drag": "module",
            "dom": "module",
            "elem": "module",
            "events": "module",
            "exports": "module",
            "ffs": "module",
            "fs": "module",
            "global": "module",
            "keyinfo": "module",
            "kpos": "module",
            "kstr": "module",
            "matchr": "module",
            "module": "module",
            "os": "module",
            "popup": "module",
            "post": "module",
            "prefs": "module",
            "process": "module",
            "setStyle": "module",
            "sds": "module",
            "slash": "module",
            "stash": "module",
            "store": "module",
            "stopEvent": "module",
            "tooltip": "module",
            "util": "module",
            "window": "module",
            "err": "function call",
            "error": "function call",
            "null": "nil",
            "false": "nil",
            "undefined": "nil",
            "require": "require",
            "of": "keyword",
            "in": "keyword",
            "is": "keyword",
            "by": "keyword",
            "or": "keyword",
            "and": "keyword",
            "not": "keyword",
            "when": "keyword",
            "unless": "keyword",
            "yes": "keyword",
            "no": "nil"
        },
        "kode": {
            "if": "keyword",
            "then": "keyword",
            "else": "keyword",
            "do": "keyword",
            "for": "keyword",
            "while": "keyword",
            "new": "keyword",
            "try": "keyword",
            "catch": "keyword",
            "throw": "keyword",
            "class": "keyword",
            "super": "keyword",
            "return": "keyword",
            "switch": "keyword",
            "break": "keyword",
            "continue": "keyword",
            "true": "keyword",
            "typeof": "keyword",
            "extends": "keyword",
            "instanceof": "keyword",
            "__dirname": "keyword",
            "__filename": "keyword",
            "Infinity": "keyword",
            "args": "module",
            "childp": "module",
            "console": "module",
            "document": "module",
            "drag": "module",
            "dom": "module",
            "elem": "module",
            "events": "module",
            "exports": "module",
            "ffs": "module",
            "fs": "module",
            "global": "module",
            "keyinfo": "module",
            "kpos": "module",
            "kstr": "module",
            "matchr": "module",
            "module": "module",
            "os": "module",
            "popup": "module",
            "post": "module",
            "prefs": "module",
            "process": "module",
            "setStyle": "module",
            "sds": "module",
            "slash": "module",
            "stash": "module",
            "store": "module",
            "stopEvent": "module",
            "tooltip": "module",
            "util": "module",
            "window": "module",
            "err": "function call",
            "error": "function call",
            "null": "nil",
            "false": "nil",
            "undefined": "nil",
            "require": "require",
            "in": "keyword",
            "is": "keyword",
            "of": "keyword",
            "or": "keyword",
            "and": "keyword",
            "not": "keyword",
            "yes": "keyword",
            "ok": "keyword",
            "when": "keyword",
            "empty": "keyword",
            "valid": "keyword",
            "noon": "keyword",
            "copy": "keyword",
            "clone": "keyword",
            "each": "keyword",
            "min": "keyword",
            "max": "keyword",
            "first": "keyword",
            "last": "keyword",
            "int": "keyword",
            "float": "keyword",
            "clamp": "keyword",
            "lpad": "keyword",
            "rpad": "keyword",
            "trim": "keyword",
            "ltrim": "keyword",
            "rtrim": "keyword",
            "function": "keyword",
            "no": "nil",
            "fail": "nil",
            "use": "require"
        },
        "js": {
            "if": "keyword",
            "then": "keyword",
            "else": "keyword",
            "do": "keyword",
            "for": "keyword",
            "while": "keyword",
            "new": "keyword",
            "try": "keyword",
            "catch": "keyword",
            "throw": "keyword",
            "class": "keyword",
            "super": "keyword",
            "return": "keyword",
            "switch": "keyword",
            "break": "keyword",
            "continue": "keyword",
            "true": "keyword",
            "typeof": "keyword",
            "extends": "keyword",
            "instanceof": "keyword",
            "__dirname": "keyword",
            "__filename": "keyword",
            "Infinity": "keyword",
            "args": "module",
            "childp": "module",
            "console": "module",
            "document": "module",
            "drag": "module",
            "dom": "module",
            "elem": "module",
            "events": "module",
            "exports": "module",
            "ffs": "module",
            "fs": "module",
            "global": "module",
            "keyinfo": "module",
            "kpos": "module",
            "kstr": "module",
            "matchr": "module",
            "module": "module",
            "os": "module",
            "popup": "module",
            "post": "module",
            "prefs": "module",
            "process": "module",
            "setStyle": "module",
            "sds": "module",
            "slash": "module",
            "stash": "module",
            "store": "module",
            "stopEvent": "module",
            "tooltip": "module",
            "util": "module",
            "window": "module",
            "err": "function call",
            "error": "function call",
            "null": "nil",
            "false": "nil",
            "undefined": "nil",
            "require": "require",
            "as": "keyword",
            "of": "keyword",
            "any": "keyword",
            "let": "keyword",
            "var": "keyword",
            "case": "keyword",
            "this": "keyword",
            "from": "keyword",
            "const": "keyword",
            "async": "keyword",
            "await": "keyword",
            "static": "keyword",
            "import": "keyword",
            "delete": "keyword",
            "function": "keyword function"
        },
        "ts": {
            "if": "keyword",
            "then": "keyword",
            "else": "keyword",
            "do": "keyword",
            "for": "keyword",
            "while": "keyword",
            "new": "keyword",
            "try": "keyword",
            "catch": "keyword",
            "throw": "keyword",
            "class": "keyword",
            "super": "keyword",
            "return": "keyword",
            "switch": "keyword",
            "break": "keyword",
            "continue": "keyword",
            "true": "keyword",
            "typeof": "keyword",
            "extends": "keyword",
            "instanceof": "keyword",
            "__dirname": "keyword",
            "__filename": "keyword",
            "Infinity": "keyword",
            "args": "module",
            "childp": "module",
            "console": "module",
            "document": "module",
            "drag": "module",
            "dom": "module",
            "elem": "module",
            "events": "module",
            "exports": "module",
            "ffs": "module",
            "fs": "module",
            "global": "module",
            "keyinfo": "module",
            "kpos": "module",
            "kstr": "module",
            "matchr": "module",
            "module": "module",
            "os": "module",
            "popup": "module",
            "post": "module",
            "prefs": "module",
            "process": "module",
            "setStyle": "module",
            "sds": "module",
            "slash": "module",
            "stash": "module",
            "store": "module",
            "stopEvent": "module",
            "tooltip": "module",
            "util": "module",
            "window": "module",
            "err": "function call",
            "error": "function call",
            "null": "nil",
            "false": "nil",
            "undefined": "nil",
            "require": "require",
            "as": "keyword",
            "of": "keyword",
            "any": "keyword",
            "let": "keyword",
            "var": "keyword",
            "case": "keyword",
            "this": "keyword",
            "from": "keyword",
            "const": "keyword",
            "async": "keyword",
            "await": "keyword",
            "static": "keyword",
            "import": "keyword",
            "delete": "keyword",
            "function": "keyword function",
            "public": "keyword type",
            "private": "keyword type",
            "protected": "keyword type",
            "abstract": "keyword type",
            "get": "keyword type",
            "set": "keyword type",
            "number": "keyword type",
            "string": "keyword type",
            "boolean": "keyword type",
            "interface": "keyword type",
            "export": "keyword type",
            "declare": "keyword type",
            "type": "keyword type",
            "void": "keyword type"
        },
        "swift": {
            "if": "keyword",
            "then": "keyword",
            "else": "keyword",
            "do": "keyword",
            "in": "keyword",
            "as": "keyword",
            "for": "keyword",
            "while": "keyword",
            "new": "keyword",
            "try": "keyword",
            "catch": "keyword",
            "throw": "keyword",
            "class": "keyword",
            "return": "keyword",
            "switch": "keyword",
            "struct": "keyword",
            "break": "keyword",
            "continue": "keyword",
            "print": "keyword",
            "true": "keyword",
            "extension": "keyword",
            "subscript": "keyword",
            "var": "keyword type",
            "let": "keyword type",
            "String": "keyword type",
            "Bool": "keyword type",
            "UInt": "keyword type",
            "Int": "keyword type",
            "Int64": "keyword type",
            "Int32": "keyword type",
            "UInt64": "keyword type",
            "UInt32": "keyword type",
            "mutating": "keyword type",
            "func": "function",
            "nil": "nil",
            "false": "nil",
            "import": "require"
        },
        "json": {
            "true": "keyword",
            "null": "nil",
            "false": "nil"
        },
        "noon": {
            "true": "keyword",
            "null": "nil",
            "false": "nil"
        },
        "yml": {
            "true": "keyword",
            "null": "nil",
            "false": "nil"
        },
        "yaml": {
            "true": "keyword",
            "null": "nil",
            "false": "nil"
        },
        "cpp": {
            "ifdef": "define",
            "undef": "define",
            "ifndef": "define",
            "define": "define",
            "endif": "define",
            "include": "define",
            "pragma": "define",
            "uniform": "define",
            "precision": "define",
            "varying": "define",
            "attribute": "define",
            "break": "keyword",
            "case": "keyword",
            "cast": "keyword",
            "cerr": "keyword",
            "class": "keyword",
            "const_cast": "keyword",
            "continue": "keyword",
            "cout": "keyword",
            "default": "keyword",
            "dynamic_cast": "keyword",
            "else": "keyword",
            "endl": "keyword",
            "enum": "keyword",
            "for": "keyword",
            "friend": "keyword",
            "if": "keyword",
            "inline": "keyword",
            "namespace": "keyword",
            "private": "keyword",
            "public": "keyword",
            "reinterpret_cast": "keyword",
            "return": "keyword",
            "sizeof": "keyword",
            "static_cast": "keyword",
            "struct": "keyword",
            "switch": "keyword",
            "template": "keyword",
            "this": "keyword",
            "true": "keyword",
            "typedef": "keyword",
            "typename": "keyword",
            "using": "keyword",
            "virtual": "keyword",
            "while": "keyword",
            "int": "keyword type",
            "auto": "keyword type",
            "void": "keyword type",
            "bool": "keyword type",
            "char": "keyword type",
            "byte": "keyword type",
            "long": "keyword type",
            "float": "keyword type",
            "double": "keyword type",
            "unsigned": "keyword type",
            "int8": "keyword type",
            "int16": "keyword type",
            "int32": "keyword type",
            "uint8": "keyword type",
            "uint16": "keyword type",
            "uint32": "keyword type",
            "int64": "keyword type",
            "uint64": "keyword type",
            "size_t": "keyword type",
            "wchar_t": "keyword type",
            "vec2": "keyword type",
            "vec3": "keyword type",
            "vec4": "keyword type",
            "ivec2": "keyword type",
            "ivec3": "keyword type",
            "ivec4": "keyword type",
            "mat2": "keyword type",
            "mat3": "keyword type",
            "mat4": "keyword type",
            "const": "punct",
            "override": "punct",
            "static": "punct",
            "out": "punct",
            "in": "punct",
            "inout": "punct",
            "err": "nil",
            "null": "nil",
            "nullptr": "nil",
            "NULL": "nil",
            "false": "nil",
            "error": "nil",
            "NAME_None": "nil",
            "iTime": "module",
            "iDate": "module",
            "iFrame": "module",
            "iMouse": "module",
            "iChannel0": "module",
            "iChannel1": "module",
            "iChannel2": "module",
            "iChannel3": "module",
            "iTimeDelta": "module",
            "iFrameRate": "module",
            "iSampleRate": "module",
            "iResolution": "module",
            "iChannelTime": "module",
            "iChannelResolution": "module"
        },
        "hpp": {
            "ifdef": "define",
            "undef": "define",
            "ifndef": "define",
            "define": "define",
            "endif": "define",
            "include": "define",
            "pragma": "define",
            "uniform": "define",
            "precision": "define",
            "varying": "define",
            "attribute": "define",
            "break": "keyword",
            "case": "keyword",
            "cast": "keyword",
            "cerr": "keyword",
            "class": "keyword",
            "const_cast": "keyword",
            "continue": "keyword",
            "cout": "keyword",
            "default": "keyword",
            "dynamic_cast": "keyword",
            "else": "keyword",
            "endl": "keyword",
            "enum": "keyword",
            "for": "keyword",
            "friend": "keyword",
            "if": "keyword",
            "inline": "keyword",
            "namespace": "keyword",
            "private": "keyword",
            "public": "keyword",
            "reinterpret_cast": "keyword",
            "return": "keyword",
            "sizeof": "keyword",
            "static_cast": "keyword",
            "struct": "keyword",
            "switch": "keyword",
            "template": "keyword",
            "this": "keyword",
            "true": "keyword",
            "typedef": "keyword",
            "typename": "keyword",
            "using": "keyword",
            "virtual": "keyword",
            "while": "keyword",
            "int": "keyword type",
            "auto": "keyword type",
            "void": "keyword type",
            "bool": "keyword type",
            "char": "keyword type",
            "byte": "keyword type",
            "long": "keyword type",
            "float": "keyword type",
            "double": "keyword type",
            "unsigned": "keyword type",
            "int8": "keyword type",
            "int16": "keyword type",
            "int32": "keyword type",
            "uint8": "keyword type",
            "uint16": "keyword type",
            "uint32": "keyword type",
            "int64": "keyword type",
            "uint64": "keyword type",
            "size_t": "keyword type",
            "wchar_t": "keyword type",
            "vec2": "keyword type",
            "vec3": "keyword type",
            "vec4": "keyword type",
            "ivec2": "keyword type",
            "ivec3": "keyword type",
            "ivec4": "keyword type",
            "mat2": "keyword type",
            "mat3": "keyword type",
            "mat4": "keyword type",
            "const": "punct",
            "override": "punct",
            "static": "punct",
            "out": "punct",
            "in": "punct",
            "inout": "punct",
            "err": "nil",
            "null": "nil",
            "nullptr": "nil",
            "NULL": "nil",
            "false": "nil",
            "error": "nil",
            "NAME_None": "nil",
            "iTime": "module",
            "iDate": "module",
            "iFrame": "module",
            "iMouse": "module",
            "iChannel0": "module",
            "iChannel1": "module",
            "iChannel2": "module",
            "iChannel3": "module",
            "iTimeDelta": "module",
            "iFrameRate": "module",
            "iSampleRate": "module",
            "iResolution": "module",
            "iChannelTime": "module",
            "iChannelResolution": "module"
        },
        "cxx": {
            "ifdef": "define",
            "undef": "define",
            "ifndef": "define",
            "define": "define",
            "endif": "define",
            "include": "define",
            "pragma": "define",
            "uniform": "define",
            "precision": "define",
            "varying": "define",
            "attribute": "define",
            "break": "keyword",
            "case": "keyword",
            "cast": "keyword",
            "cerr": "keyword",
            "class": "keyword",
            "const_cast": "keyword",
            "continue": "keyword",
            "cout": "keyword",
            "default": "keyword",
            "dynamic_cast": "keyword",
            "else": "keyword",
            "endl": "keyword",
            "enum": "keyword",
            "for": "keyword",
            "friend": "keyword",
            "if": "keyword",
            "inline": "keyword",
            "namespace": "keyword",
            "private": "keyword",
            "public": "keyword",
            "reinterpret_cast": "keyword",
            "return": "keyword",
            "sizeof": "keyword",
            "static_cast": "keyword",
            "struct": "keyword",
            "switch": "keyword",
            "template": "keyword",
            "this": "keyword",
            "true": "keyword",
            "typedef": "keyword",
            "typename": "keyword",
            "using": "keyword",
            "virtual": "keyword",
            "while": "keyword",
            "int": "keyword type",
            "auto": "keyword type",
            "void": "keyword type",
            "bool": "keyword type",
            "char": "keyword type",
            "byte": "keyword type",
            "long": "keyword type",
            "float": "keyword type",
            "double": "keyword type",
            "unsigned": "keyword type",
            "int8": "keyword type",
            "int16": "keyword type",
            "int32": "keyword type",
            "uint8": "keyword type",
            "uint16": "keyword type",
            "uint32": "keyword type",
            "int64": "keyword type",
            "uint64": "keyword type",
            "size_t": "keyword type",
            "wchar_t": "keyword type",
            "vec2": "keyword type",
            "vec3": "keyword type",
            "vec4": "keyword type",
            "ivec2": "keyword type",
            "ivec3": "keyword type",
            "ivec4": "keyword type",
            "mat2": "keyword type",
            "mat3": "keyword type",
            "mat4": "keyword type",
            "const": "punct",
            "override": "punct",
            "static": "punct",
            "out": "punct",
            "in": "punct",
            "inout": "punct",
            "err": "nil",
            "null": "nil",
            "nullptr": "nil",
            "NULL": "nil",
            "false": "nil",
            "error": "nil",
            "NAME_None": "nil",
            "iTime": "module",
            "iDate": "module",
            "iFrame": "module",
            "iMouse": "module",
            "iChannel0": "module",
            "iChannel1": "module",
            "iChannel2": "module",
            "iChannel3": "module",
            "iTimeDelta": "module",
            "iFrameRate": "module",
            "iSampleRate": "module",
            "iResolution": "module",
            "iChannelTime": "module",
            "iChannelResolution": "module"
        },
        "mm": {
            "ifdef": "define",
            "undef": "define",
            "ifndef": "define",
            "define": "define",
            "endif": "define",
            "include": "define",
            "pragma": "define",
            "uniform": "define",
            "precision": "define",
            "varying": "define",
            "attribute": "define",
            "break": "keyword",
            "case": "keyword",
            "cast": "keyword",
            "cerr": "keyword",
            "class": "keyword",
            "const_cast": "keyword",
            "continue": "keyword",
            "cout": "keyword",
            "default": "keyword",
            "dynamic_cast": "keyword",
            "else": "keyword",
            "endl": "keyword",
            "enum": "keyword",
            "for": "keyword",
            "friend": "keyword",
            "if": "keyword",
            "inline": "keyword",
            "namespace": "keyword",
            "private": "keyword",
            "public": "keyword",
            "reinterpret_cast": "keyword",
            "return": "keyword",
            "sizeof": "keyword",
            "static_cast": "keyword",
            "struct": "keyword",
            "switch": "keyword",
            "template": "keyword",
            "this": "keyword",
            "true": "keyword",
            "typedef": "keyword",
            "typename": "keyword",
            "using": "keyword",
            "virtual": "keyword",
            "while": "keyword",
            "int": "keyword type",
            "auto": "keyword type",
            "void": "keyword type",
            "bool": "keyword type",
            "char": "keyword type",
            "byte": "keyword type",
            "long": "keyword type",
            "float": "keyword type",
            "double": "keyword type",
            "unsigned": "keyword type",
            "int8": "keyword type",
            "int16": "keyword type",
            "int32": "keyword type",
            "uint8": "keyword type",
            "uint16": "keyword type",
            "uint32": "keyword type",
            "int64": "keyword type",
            "uint64": "keyword type",
            "size_t": "keyword type",
            "wchar_t": "keyword type",
            "vec2": "keyword type",
            "vec3": "keyword type",
            "vec4": "keyword type",
            "ivec2": "keyword type",
            "ivec3": "keyword type",
            "ivec4": "keyword type",
            "mat2": "keyword type",
            "mat3": "keyword type",
            "mat4": "keyword type",
            "const": "punct",
            "override": "punct",
            "static": "punct",
            "out": "punct",
            "in": "keyword",
            "inout": "punct",
            "err": "nil",
            "null": "nil",
            "nullptr": "nil",
            "NULL": "nil",
            "false": "nil",
            "error": "nil",
            "NAME_None": "nil",
            "iTime": "module",
            "iDate": "module",
            "iFrame": "module",
            "iMouse": "module",
            "iChannel0": "module",
            "iChannel1": "module",
            "iChannel2": "module",
            "iChannel3": "module",
            "iTimeDelta": "module",
            "iFrameRate": "module",
            "iSampleRate": "module",
            "iResolution": "module",
            "iChannelTime": "module",
            "iChannelResolution": "module",
            "defaultManager": "method",
            "__block": "property",
            "nonatomic": "property",
            "readwrite": "property",
            "assign": "property",
            "retain": "property",
            "path": "property",
            "id": "keyword",
            "self": "keyword",
            "super": "keyword",
            "alloc": "keyword",
            "init": "keyword",
            "count": "keyword",
            "length": "keyword",
            "release": "keyword",
            "array": "keyword",
            "dictionary": "keyword",
            "longValue": "keyword",
            "autorelease": "keyword",
            "isKindOfClass": "keyword",
            "generalPasteboard": "keyword",
            "sharedApplication": "keyword",
            "mainBundle": "keyword",
            "setObject": "keyword",
            "hasPrefix": "keyword",
            "hasSuffix": "keyword",
            "setString": "keyword",
            "forType": "keyword",
            "appendString": "keyword",
            "stringWithString": "keyword",
            "completionHandler": "keyword",
            "dataWithJSONObject": "keyword",
            "forKey": "keyword",
            "addObject": "keyword",
            "isDirectory": "keyword",
            "writeToFile": "keyword",
            "initWithData": "keyword",
            "valueForKey": "keyword",
            "objectForKey": "keyword",
            "objectAtIndex": "keyword",
            "trashItemAtURL": "keyword",
            "resultingItemURL": "keyword",
            "numberWithBool": "keyword",
            "moveItemAtPath": "keyword",
            "copyItemAtPath": "keyword",
            "toPath": "keyword",
            "nextObject": "keyword",
            "skipDescendants": "keyword",
            "floatValue": "keyword",
            "numberWithInt": "keyword",
            "numberWithLong": "keyword",
            "numberWithFloat": "keyword",
            "fileURLWithPath": "keyword",
            "removeItemAtPath": "keyword",
            "enumeratorAtPath": "keyword",
            "fileExistsAtPath": "keyword",
            "dataUsingEncoding": "keyword",
            "isWritableFileAtPath": "keyword",
            "createDirectoryAtPath": "keyword",
            "withIntermediateDirectories": "keyword",
            "attributesOfItemAtPath": "keyword",
            "isReadableFileAtPath": "keyword",
            "addObjectsFromArray": "keyword",
            "substringFromIndex": "keyword",
            "pathWithComponents": "keyword",
            "pathExtension": "keyword",
            "performSelector": "keyword",
            "evaluateJavaScript": "keyword",
            "cStringUsingEncoding": "keyword",
            "characterSetWithCharactersInString": "keyword",
            "componentsSeparatedByCharactersInSet": "keyword",
            "arrayByAddingObject": "keyword",
            "arrayWithObject": "keyword",
            "arrayWithObjects": "keyword",
            "stringForType": "keyword",
            "stringWithFormat": "keyword",
            "stringByAppendingString": "keyword",
            "stringByStandardizingPath": "keyword",
            "stringByExpandingTildeInPath": "keyword",
            "stringByDeletingPathExtension": "keyword",
            "stringByAppendingPathComponent": "keyword",
            "stringWithContentsOfFile": "keyword",
            "componentsJoinedByString": "keyword",
            "isEqualToString": "keyword",
            "dictionaryWithObjectsAndKeys": "keyword",
            "options": "keyword",
            "encoding": "keyword",
            "attributes": "keyword",
            "configuration": "keyword",
            "delegate": "keyword",
            "YES": "keyword",
            "BOOL": "keyword",
            "end": "define",
            "import": "define",
            "synthesize": "define",
            "implementation": "define",
            "interface": "define",
            "property": "define",
            "nil": "nil",
            "NO": "nil",
            "NSError": "nil",
            "NSNotFound": "nil",
            "Win": "module",
            "View": "module",
            "NSWindow": "module",
            "NSBundle": "module",
            "WKWebView": "module",
            "NSWorkspace": "module",
            "NSMutableSet": "module",
            "WKNavigation": "module",
            "NSURLRequest": "module",
            "NSPasteboard": "module",
            "NSFileManager": "module",
            "NSApplication": "module",
            "NSCharacterSet": "module",
            "NSNotification": "module",
            "WKContentWorld": "module",
            "WKScriptMessage": "module",
            "NSBitmapImageRep": "module",
            "WKWebsiteDataStore": "module",
            "NSJSONSerialization": "module",
            "NSImageDataBitmapRep": "module",
            "NSRunningApplication": "module",
            "NSDirectoryEnumerator": "module",
            "WKWebViewConfiguration": "module",
            "WKSnapshotConfiguration": "module",
            "NSSet": "type",
            "NSURL": "type",
            "NSObject": "type",
            "NSValue": "type",
            "CGRect": "type",
            "NSImage": "type",
            "NSPoint": "type",
            "NSDate": "type",
            "NSData": "type",
            "NSArray": "type",
            "NSNumber": "type",
            "NSString": "type",
            "NSFileType": "type",
            "NSDictionary": "type",
            "NSMutableArray": "type",
            "NSMutableString": "type",
            "NSMutableDictionary": "type",
            "NSApplicationActivationPolicyRegular": "type",
            "WKInactiveSchedulingPolicyNone": "type",
            "NSWorkspaceOpenConfiguration": "type",
            "NSApplicationTerminateReply": "type",
            "NSJSONWritingPrettyPrinted": "type",
            "NSBitmapImageFileTypePNG": "type",
            "WKUserContentController": "type",
            "NSPasteboardTypeString": "type",
            "NSUTF8StringEncoding": "type",
            "NSFileTypeDirectory": "type",
            "NSTimeInterval": "type",
            "NSOrderedSame": "type",
            "NSAtomicWrite": "type",
            "NSUInteger": "type",
            "NSInteger": "type",
            "NSRect": "type"
        },
        "c": {
            "ifdef": "define",
            "undef": "define",
            "ifndef": "define",
            "define": "define",
            "endif": "define",
            "include": "define",
            "pragma": "define",
            "uniform": "define",
            "precision": "define",
            "varying": "define",
            "attribute": "define",
            "break": "keyword",
            "case": "keyword",
            "cast": "keyword",
            "cerr": "keyword",
            "class": "keyword",
            "const_cast": "keyword",
            "continue": "keyword",
            "cout": "keyword",
            "default": "keyword",
            "dynamic_cast": "keyword",
            "else": "keyword",
            "endl": "keyword",
            "enum": "keyword",
            "for": "keyword",
            "friend": "keyword",
            "if": "keyword",
            "inline": "keyword",
            "namespace": "keyword",
            "private": "keyword",
            "public": "keyword",
            "reinterpret_cast": "keyword",
            "return": "keyword",
            "sizeof": "keyword",
            "static_cast": "keyword",
            "struct": "keyword",
            "switch": "keyword",
            "template": "keyword",
            "this": "keyword",
            "true": "keyword",
            "typedef": "keyword",
            "typename": "keyword",
            "using": "keyword",
            "virtual": "keyword",
            "while": "keyword",
            "int": "keyword type",
            "auto": "keyword type",
            "void": "keyword type",
            "bool": "keyword type",
            "char": "keyword type",
            "byte": "keyword type",
            "long": "keyword type",
            "float": "keyword type",
            "double": "keyword type",
            "unsigned": "keyword type",
            "int8": "keyword type",
            "int16": "keyword type",
            "int32": "keyword type",
            "uint8": "keyword type",
            "uint16": "keyword type",
            "uint32": "keyword type",
            "int64": "keyword type",
            "uint64": "keyword type",
            "size_t": "keyword type",
            "wchar_t": "keyword type",
            "vec2": "keyword type",
            "vec3": "keyword type",
            "vec4": "keyword type",
            "ivec2": "keyword type",
            "ivec3": "keyword type",
            "ivec4": "keyword type",
            "mat2": "keyword type",
            "mat3": "keyword type",
            "mat4": "keyword type",
            "const": "punct",
            "override": "punct",
            "static": "punct",
            "out": "punct",
            "in": "punct",
            "inout": "punct",
            "err": "nil",
            "null": "nil",
            "nullptr": "nil",
            "NULL": "nil",
            "false": "nil",
            "error": "nil",
            "NAME_None": "nil",
            "iTime": "module",
            "iDate": "module",
            "iFrame": "module",
            "iMouse": "module",
            "iChannel0": "module",
            "iChannel1": "module",
            "iChannel2": "module",
            "iChannel3": "module",
            "iTimeDelta": "module",
            "iFrameRate": "module",
            "iSampleRate": "module",
            "iResolution": "module",
            "iChannelTime": "module",
            "iChannelResolution": "module"
        },
        "h": {
            "ifdef": "define",
            "undef": "define",
            "ifndef": "define",
            "define": "define",
            "endif": "define",
            "include": "define",
            "pragma": "define",
            "uniform": "define",
            "precision": "define",
            "varying": "define",
            "attribute": "define",
            "break": "keyword",
            "case": "keyword",
            "cast": "keyword",
            "cerr": "keyword",
            "class": "keyword",
            "const_cast": "keyword",
            "continue": "keyword",
            "cout": "keyword",
            "default": "keyword",
            "dynamic_cast": "keyword",
            "else": "keyword",
            "endl": "keyword",
            "enum": "keyword",
            "for": "keyword",
            "friend": "keyword",
            "if": "keyword",
            "inline": "keyword",
            "namespace": "keyword",
            "private": "keyword",
            "public": "keyword",
            "reinterpret_cast": "keyword",
            "return": "keyword",
            "sizeof": "keyword",
            "static_cast": "keyword",
            "struct": "keyword",
            "switch": "keyword",
            "template": "keyword",
            "this": "keyword",
            "true": "keyword",
            "typedef": "keyword",
            "typename": "keyword",
            "using": "keyword",
            "virtual": "keyword",
            "while": "keyword",
            "int": "keyword type",
            "auto": "keyword type",
            "void": "keyword type",
            "bool": "keyword type",
            "char": "keyword type",
            "byte": "keyword type",
            "long": "keyword type",
            "float": "keyword type",
            "double": "keyword type",
            "unsigned": "keyword type",
            "int8": "keyword type",
            "int16": "keyword type",
            "int32": "keyword type",
            "uint8": "keyword type",
            "uint16": "keyword type",
            "uint32": "keyword type",
            "int64": "keyword type",
            "uint64": "keyword type",
            "size_t": "keyword type",
            "wchar_t": "keyword type",
            "vec2": "keyword type",
            "vec3": "keyword type",
            "vec4": "keyword type",
            "ivec2": "keyword type",
            "ivec3": "keyword type",
            "ivec4": "keyword type",
            "mat2": "keyword type",
            "mat3": "keyword type",
            "mat4": "keyword type",
            "const": "punct",
            "override": "punct",
            "static": "punct",
            "out": "punct",
            "in": "punct",
            "inout": "punct",
            "err": "nil",
            "null": "nil",
            "nullptr": "nil",
            "NULL": "nil",
            "false": "nil",
            "error": "nil",
            "NAME_None": "nil",
            "iTime": "module",
            "iDate": "module",
            "iFrame": "module",
            "iMouse": "module",
            "iChannel0": "module",
            "iChannel1": "module",
            "iChannel2": "module",
            "iChannel3": "module",
            "iTimeDelta": "module",
            "iFrameRate": "module",
            "iSampleRate": "module",
            "iResolution": "module",
            "iChannelTime": "module",
            "iChannelResolution": "module"
        },
        "cs": {
            "ifdef": "define",
            "undef": "define",
            "ifndef": "define",
            "define": "define",
            "endif": "define",
            "include": "define",
            "pragma": "define",
            "uniform": "define",
            "precision": "define",
            "varying": "define",
            "attribute": "define",
            "break": "keyword",
            "case": "keyword",
            "cast": "keyword",
            "cerr": "keyword",
            "class": "keyword",
            "const_cast": "keyword",
            "continue": "keyword",
            "cout": "keyword",
            "default": "keyword",
            "dynamic_cast": "keyword",
            "else": "keyword",
            "endl": "keyword",
            "enum": "keyword",
            "for": "keyword",
            "friend": "keyword",
            "if": "keyword",
            "inline": "keyword",
            "namespace": "keyword",
            "private": "keyword",
            "public": "keyword",
            "reinterpret_cast": "keyword",
            "return": "keyword",
            "sizeof": "keyword",
            "static_cast": "keyword",
            "struct": "keyword",
            "switch": "keyword",
            "template": "keyword",
            "this": "keyword",
            "true": "keyword",
            "typedef": "keyword",
            "typename": "keyword",
            "using": "keyword",
            "virtual": "keyword",
            "while": "keyword",
            "int": "keyword type",
            "auto": "keyword type",
            "void": "keyword type",
            "bool": "keyword type",
            "char": "keyword type",
            "byte": "keyword type",
            "long": "keyword type",
            "float": "keyword type",
            "double": "keyword type",
            "unsigned": "keyword type",
            "int8": "keyword type",
            "int16": "keyword type",
            "int32": "keyword type",
            "uint8": "keyword type",
            "uint16": "keyword type",
            "uint32": "keyword type",
            "int64": "keyword type",
            "uint64": "keyword type",
            "size_t": "keyword type",
            "wchar_t": "keyword type",
            "vec2": "keyword type",
            "vec3": "keyword type",
            "vec4": "keyword type",
            "ivec2": "keyword type",
            "ivec3": "keyword type",
            "ivec4": "keyword type",
            "mat2": "keyword type",
            "mat3": "keyword type",
            "mat4": "keyword type",
            "const": "punct",
            "override": "punct",
            "static": "punct",
            "out": "punct",
            "in": "punct",
            "inout": "punct",
            "err": "nil",
            "null": "nil",
            "nullptr": "nil",
            "NULL": "nil",
            "false": "nil",
            "error": "nil",
            "NAME_None": "nil",
            "iTime": "module",
            "iDate": "module",
            "iFrame": "module",
            "iMouse": "module",
            "iChannel0": "module",
            "iChannel1": "module",
            "iChannel2": "module",
            "iChannel3": "module",
            "iTimeDelta": "module",
            "iFrameRate": "module",
            "iSampleRate": "module",
            "iResolution": "module",
            "iChannelTime": "module",
            "iChannelResolution": "module"
        },
        "frag": {
            "ifdef": "define",
            "undef": "define",
            "ifndef": "define",
            "define": "define",
            "endif": "define",
            "include": "define",
            "pragma": "define",
            "uniform": "define",
            "precision": "define",
            "varying": "define",
            "attribute": "define",
            "break": "keyword",
            "case": "keyword",
            "cast": "keyword",
            "cerr": "keyword",
            "class": "keyword",
            "const_cast": "keyword",
            "continue": "keyword",
            "cout": "keyword",
            "default": "keyword",
            "dynamic_cast": "keyword",
            "else": "keyword",
            "endl": "keyword",
            "enum": "keyword",
            "for": "keyword",
            "friend": "keyword",
            "if": "keyword",
            "inline": "keyword",
            "namespace": "keyword",
            "private": "keyword",
            "public": "keyword",
            "reinterpret_cast": "keyword",
            "return": "keyword",
            "sizeof": "keyword",
            "static_cast": "keyword",
            "struct": "keyword",
            "switch": "keyword",
            "template": "keyword",
            "this": "keyword",
            "true": "keyword",
            "typedef": "keyword",
            "typename": "keyword",
            "using": "keyword",
            "virtual": "keyword",
            "while": "keyword",
            "int": "keyword type",
            "auto": "keyword type",
            "void": "keyword type",
            "bool": "keyword type",
            "char": "keyword type",
            "byte": "keyword type",
            "long": "keyword type",
            "float": "keyword type",
            "double": "keyword type",
            "unsigned": "keyword type",
            "int8": "keyword type",
            "int16": "keyword type",
            "int32": "keyword type",
            "uint8": "keyword type",
            "uint16": "keyword type",
            "uint32": "keyword type",
            "int64": "keyword type",
            "uint64": "keyword type",
            "size_t": "keyword type",
            "wchar_t": "keyword type",
            "vec2": "keyword type",
            "vec3": "keyword type",
            "vec4": "keyword type",
            "ivec2": "keyword type",
            "ivec3": "keyword type",
            "ivec4": "keyword type",
            "mat2": "keyword type",
            "mat3": "keyword type",
            "mat4": "keyword type",
            "const": "punct",
            "override": "punct",
            "static": "punct",
            "out": "punct",
            "in": "punct",
            "inout": "punct",
            "err": "nil",
            "null": "nil",
            "nullptr": "nil",
            "NULL": "nil",
            "false": "nil",
            "error": "nil",
            "NAME_None": "nil",
            "iTime": "module",
            "iDate": "module",
            "iFrame": "module",
            "iMouse": "module",
            "iChannel0": "module",
            "iChannel1": "module",
            "iChannel2": "module",
            "iChannel3": "module",
            "iTimeDelta": "module",
            "iFrameRate": "module",
            "iSampleRate": "module",
            "iResolution": "module",
            "iChannelTime": "module",
            "iChannelResolution": "module"
        },
        "vert": {
            "ifdef": "define",
            "undef": "define",
            "ifndef": "define",
            "define": "define",
            "endif": "define",
            "include": "define",
            "pragma": "define",
            "uniform": "define",
            "precision": "define",
            "varying": "define",
            "attribute": "define",
            "break": "keyword",
            "case": "keyword",
            "cast": "keyword",
            "cerr": "keyword",
            "class": "keyword",
            "const_cast": "keyword",
            "continue": "keyword",
            "cout": "keyword",
            "default": "keyword",
            "dynamic_cast": "keyword",
            "else": "keyword",
            "endl": "keyword",
            "enum": "keyword",
            "for": "keyword",
            "friend": "keyword",
            "if": "keyword",
            "inline": "keyword",
            "namespace": "keyword",
            "private": "keyword",
            "public": "keyword",
            "reinterpret_cast": "keyword",
            "return": "keyword",
            "sizeof": "keyword",
            "static_cast": "keyword",
            "struct": "keyword",
            "switch": "keyword",
            "template": "keyword",
            "this": "keyword",
            "true": "keyword",
            "typedef": "keyword",
            "typename": "keyword",
            "using": "keyword",
            "virtual": "keyword",
            "while": "keyword",
            "int": "keyword type",
            "auto": "keyword type",
            "void": "keyword type",
            "bool": "keyword type",
            "char": "keyword type",
            "byte": "keyword type",
            "long": "keyword type",
            "float": "keyword type",
            "double": "keyword type",
            "unsigned": "keyword type",
            "int8": "keyword type",
            "int16": "keyword type",
            "int32": "keyword type",
            "uint8": "keyword type",
            "uint16": "keyword type",
            "uint32": "keyword type",
            "int64": "keyword type",
            "uint64": "keyword type",
            "size_t": "keyword type",
            "wchar_t": "keyword type",
            "vec2": "keyword type",
            "vec3": "keyword type",
            "vec4": "keyword type",
            "ivec2": "keyword type",
            "ivec3": "keyword type",
            "ivec4": "keyword type",
            "mat2": "keyword type",
            "mat3": "keyword type",
            "mat4": "keyword type",
            "const": "punct",
            "override": "punct",
            "static": "punct",
            "out": "punct",
            "in": "punct",
            "inout": "punct",
            "err": "nil",
            "null": "nil",
            "nullptr": "nil",
            "NULL": "nil",
            "false": "nil",
            "error": "nil",
            "NAME_None": "nil",
            "iTime": "module",
            "iDate": "module",
            "iFrame": "module",
            "iMouse": "module",
            "iChannel0": "module",
            "iChannel1": "module",
            "iChannel2": "module",
            "iChannel3": "module",
            "iTimeDelta": "module",
            "iFrameRate": "module",
            "iSampleRate": "module",
            "iResolution": "module",
            "iChannelTime": "module",
            "iChannelResolution": "module"
        },
        "html": {
            "a": "keyword",
            "b": "keyword",
            "p": "keyword",
            "ul": "keyword",
            "li": "keyword",
            "br": "keyword",
            "tr": "keyword",
            "th": "keyword",
            "td": "keyword",
            "dt": "keyword",
            "hr": "keyword",
            "h1": "keyword",
            "h2": "keyword",
            "h3": "keyword",
            "h4": "keyword",
            "h5": "keyword",
            "div": "keyword",
            "nav": "keyword",
            "img": "keyword",
            "pre": "keyword",
            "map": "keyword",
            "area": "keyword",
            "html": "keyword",
            "head": "keyword",
            "meta": "keyword",
            "body": "keyword",
            "span": "keyword",
            "link": "keyword",
            "input": "keyword",
            "button": "keyword",
            "section": "keyword",
            "header": "keyword",
            "footer": "keyword",
            "script": "keyword",
            "style": "property",
            "table": "keyword",
            "title": "keyword",
            "blockquote": "keyword",
            "center": "keyword",
            "canvas": "keyword",
            "doctype": "keyword",
            "DOCTYPE": "keyword",
            "g": "keyword",
            "svg": "keyword",
            "path": "keyword",
            "rect": "keyword",
            "line": "keyword",
            "defs": "keyword",
            "text": "keyword",
            "tspan": "keyword",
            "circle": "keyword",
            "ellipse": "keyword",
            "polygon": "keyword",
            "polyline": "keyword",
            "pattern": "keyword",
            "filter": "keyword",
            "stop": "keyword",
            "radialgradient": "keyword",
            "lineargradient": "keyword",
            "id": "property",
            "type": "property",
            "href": "property",
            "src": "property",
            "rel": "property",
            "lang": "property",
            "class": "property",
            "name": "property",
            "width": "property",
            "height": "property",
            "media": "property",
            "value": "property",
            "shape": "property",
            "coords": "property",
            "content": "property",
            "charset": "property",
            "viewbox": "property",
            "tabindex": "property",
            "onmouseover": "property",
            "onmouseout": "property"
        },
        "htm": {
            "a": "keyword",
            "b": "keyword",
            "p": "keyword",
            "ul": "keyword",
            "li": "keyword",
            "br": "keyword",
            "tr": "keyword",
            "th": "keyword",
            "td": "keyword",
            "dt": "keyword",
            "hr": "keyword",
            "h1": "keyword",
            "h2": "keyword",
            "h3": "keyword",
            "h4": "keyword",
            "h5": "keyword",
            "div": "keyword",
            "nav": "keyword",
            "img": "keyword",
            "pre": "keyword",
            "map": "keyword",
            "area": "keyword",
            "html": "keyword",
            "head": "keyword",
            "meta": "keyword",
            "body": "keyword",
            "span": "keyword",
            "link": "keyword",
            "input": "keyword",
            "button": "keyword",
            "section": "keyword",
            "header": "keyword",
            "footer": "keyword",
            "script": "keyword",
            "style": "property",
            "table": "keyword",
            "title": "keyword",
            "blockquote": "keyword",
            "center": "keyword",
            "canvas": "keyword",
            "doctype": "keyword",
            "DOCTYPE": "keyword",
            "g": "keyword",
            "svg": "keyword",
            "path": "keyword",
            "rect": "keyword",
            "line": "keyword",
            "defs": "keyword",
            "text": "keyword",
            "tspan": "keyword",
            "circle": "keyword",
            "ellipse": "keyword",
            "polygon": "keyword",
            "polyline": "keyword",
            "pattern": "keyword",
            "filter": "keyword",
            "stop": "keyword",
            "radialgradient": "keyword",
            "lineargradient": "keyword",
            "id": "property",
            "type": "property",
            "href": "property",
            "src": "property",
            "rel": "property",
            "lang": "property",
            "class": "property",
            "name": "property",
            "width": "property",
            "height": "property",
            "media": "property",
            "value": "property",
            "shape": "property",
            "coords": "property",
            "content": "property",
            "charset": "property",
            "viewbox": "property",
            "tabindex": "property",
            "onmouseover": "property",
            "onmouseout": "property"
        },
        "pug": {
            "a": "keyword",
            "b": "keyword",
            "p": "keyword",
            "ul": "keyword",
            "li": "keyword",
            "br": "keyword",
            "tr": "keyword",
            "th": "keyword",
            "td": "keyword",
            "dt": "keyword",
            "hr": "keyword",
            "h1": "keyword",
            "h2": "keyword",
            "h3": "keyword",
            "h4": "keyword",
            "h5": "keyword",
            "div": "keyword",
            "nav": "keyword",
            "img": "keyword",
            "pre": "keyword",
            "map": "keyword",
            "area": "keyword",
            "html": "keyword",
            "head": "keyword",
            "meta": "keyword",
            "body": "keyword",
            "span": "keyword",
            "link": "keyword",
            "input": "keyword",
            "button": "keyword",
            "section": "keyword",
            "header": "keyword",
            "footer": "keyword",
            "script": "keyword",
            "style": "property",
            "table": "keyword",
            "title": "keyword",
            "blockquote": "keyword",
            "center": "keyword",
            "canvas": "keyword",
            "doctype": "keyword",
            "DOCTYPE": "keyword",
            "g": "keyword",
            "svg": "keyword",
            "path": "keyword",
            "rect": "keyword",
            "line": "keyword",
            "defs": "keyword",
            "text": "keyword",
            "tspan": "keyword",
            "circle": "keyword",
            "ellipse": "keyword",
            "polygon": "keyword",
            "polyline": "keyword",
            "pattern": "keyword",
            "filter": "keyword",
            "stop": "keyword",
            "radialgradient": "keyword",
            "lineargradient": "keyword",
            "id": "property",
            "type": "property",
            "href": "property",
            "src": "property",
            "rel": "property",
            "lang": "property",
            "class": "property",
            "name": "property",
            "width": "property",
            "height": "property",
            "media": "property",
            "value": "property",
            "shape": "property",
            "coords": "property",
            "content": "property",
            "charset": "property",
            "viewbox": "property",
            "tabindex": "property",
            "onmouseover": "property",
            "onmouseout": "property"
        },
        "md": {
            "a": "keyword",
            "b": "keyword",
            "p": "keyword",
            "ul": "keyword",
            "li": "keyword",
            "br": "keyword",
            "tr": "keyword",
            "th": "keyword",
            "td": "keyword",
            "dt": "keyword",
            "hr": "keyword",
            "h1": "keyword",
            "h2": "keyword",
            "h3": "keyword",
            "h4": "keyword",
            "h5": "keyword",
            "div": "keyword",
            "nav": "keyword",
            "img": "keyword",
            "pre": "keyword",
            "map": "keyword",
            "area": "keyword",
            "html": "keyword",
            "head": "keyword",
            "meta": "keyword",
            "body": "keyword",
            "span": "keyword",
            "link": "keyword",
            "input": "keyword",
            "button": "keyword",
            "section": "keyword",
            "header": "keyword",
            "footer": "keyword",
            "script": "keyword",
            "style": "keyword",
            "table": "keyword",
            "title": "keyword",
            "blockquote": "keyword",
            "center": "keyword",
            "canvas": "keyword",
            "doctype": "keyword",
            "DOCTYPE": "keyword",
            "true": "keyword",
            "false": "nil"
        },
        "styl": {
            "a": "keyword",
            "b": "keyword",
            "p": "keyword",
            "ul": "keyword",
            "li": "keyword",
            "br": "keyword",
            "tr": "keyword",
            "th": "keyword",
            "td": "keyword",
            "dt": "keyword",
            "hr": "keyword",
            "h1": "keyword",
            "h2": "keyword",
            "h3": "keyword",
            "h4": "keyword",
            "h5": "keyword",
            "div": "keyword",
            "nav": "keyword",
            "img": "keyword",
            "pre": "keyword",
            "map": "keyword",
            "area": "keyword",
            "html": "keyword",
            "head": "keyword",
            "meta": "keyword",
            "body": "keyword",
            "span": "keyword",
            "link": "keyword",
            "input": "keyword",
            "button": "keyword",
            "section": "keyword",
            "header": "keyword",
            "footer": "keyword",
            "script": "keyword",
            "style": "keyword",
            "table": "keyword",
            "title": "keyword",
            "blockquote": "keyword",
            "center": "keyword",
            "canvas": "keyword",
            "doctype": "keyword",
            "DOCTYPE": "keyword",
            "absolute": "argument",
            "all": "argument",
            "antialiased": "argument",
            "auto": "argument",
            "block": "argument",
            "bold": "argument",
            "border": "keyword",
            "bottom": "keyword",
            "box": "keyword",
            "column": "keyword",
            "default": "argument",
            "dotted": "argument",
            "drag": "argument",
            "ease": "argument",
            "ew": "argument",
            "fadein": "argument",
            "flex": "keyword",
            "forwards": "argument",
            "from": "argument",
            "grab": "argument",
            "grid": "keyword",
            "hidden": "argument",
            "in": "argument",
            "initial": "argument",
            "inline": "argument",
            "inset": "argument",
            "italic": "argument",
            "justify": "argument",
            "larger": "argument",
            "left": "keyword",
            "lr": "argument",
            "middle": "argument",
            "move": "argument",
            "no": "argument",
            "normal": "argument",
            "nowrap": "argument",
            "ns": "argument",
            "out": "argument",
            "pointer": "keyword",
            "relative": "argument",
            "repeat": "keyword",
            "resize": "keyword",
            "right": "keyword",
            "round": "argument",
            "row": "argument",
            "scalex": "argument",
            "scaley": "argument",
            "scroll": "argument",
            "smaller": "argument",
            "solid": "argument",
            "static": "argument",
            "text": "keyword",
            "to": "argument",
            "top": "keyword",
            "translate": "argument",
            "translate3d": "argument",
            "translatex": "argument",
            "translatey": "argument",
            "translatez": "argument",
            "transparent": "argument",
            "underline": "argument",
            "uppercase": "argument",
            "vertical": "keyword",
            "visible": "argument",
            "red": "property color",
            "green": "property color",
            "blue": "property color",
            "yellow": "property color",
            "magenta": "property color",
            "cyan": "property color",
            "black": "property color",
            "gray": "property color",
            "white": "keyword",
            "orange": "property color",
            "abs": "keyword",
            "after": "keyword",
            "align": "keyword",
            "animation": "keyword",
            "app": "keyword",
            "background": "keyword",
            "before": "keyword",
            "blend": "keyword",
            "caret": "keyword",
            "clip": "keyword",
            "color": "keyword",
            "content": "keyword",
            "corner": "keyword",
            "count": "keyword",
            "cursor": "keyword",
            "dasharray": "keyword",
            "dashoffset": "keyword",
            "decoration": "keyword",
            "delay": "keyword",
            "direction": "keyword",
            "display": "keyword",
            "duration": "keyword",
            "events": "keyword",
            "family": "keyword",
            "fill": "keyword",
            "filter": "keyword",
            "float": "keyword",
            "flow": "keyword",
            "font": "keyword",
            "function": "keyword",
            "grow": "keyword",
            "height": "keyword",
            "image": "keyword",
            "index": "keyword",
            "iteration": "keyword",
            "line": "keyword",
            "linecap": "keyword",
            "linejoin": "keyword",
            "list": "keyword",
            "margin": "keyword",
            "max": "keyword",
            "min": "keyword",
            "mode": "keyword",
            "opacity": "keyword",
            "origin": "keyword",
            "outline": "keyword",
            "overflow": "keyword",
            "padding": "keyword",
            "position": "keyword",
            "property": "keyword",
            "radius": "keyword",
            "region": "keyword",
            "scrollbar": "keyword",
            "select": "keyword",
            "selection": "keyword",
            "shadow": "function",
            "shrink": "keyword",
            "size": "keyword",
            "sizing": "keyword",
            "smoothing": "keyword",
            "space": "keyword",
            "start": "keyword",
            "stroke": "keyword",
            "thumb": "keyword",
            "timing": "keyword",
            "track": "keyword",
            "transform": "keyword",
            "transition": "keyword",
            "type": "keyword",
            "user": "keyword",
            "webkit": "keyword",
            "weight": "keyword",
            "width": "keyword",
            "word": "keyword",
            "writing": "keyword",
            "x": "keyword",
            "y": "keyword",
            "z": "keyword",
            "zoom": "keyword",
            "rgb": "function",
            "rgba": "function",
            "drop": "function",
            "linear": "function",
            "gradient": "function",
            "important": "important",
            "not": "property special",
            "hover": "property special",
            "focus": "property special",
            "active": "property special",
            "first": "property special",
            "last": "property special",
            "nth": "property special",
            "child": "property special",
            "none": "nil"
        },
        "css": {
            "a": "keyword",
            "b": "keyword",
            "p": "keyword",
            "ul": "keyword",
            "li": "keyword",
            "br": "keyword",
            "tr": "keyword",
            "th": "keyword",
            "td": "keyword",
            "dt": "keyword",
            "hr": "keyword",
            "h1": "keyword",
            "h2": "keyword",
            "h3": "keyword",
            "h4": "keyword",
            "h5": "keyword",
            "div": "keyword",
            "nav": "keyword",
            "img": "keyword",
            "pre": "keyword",
            "map": "keyword",
            "area": "keyword",
            "html": "keyword",
            "head": "keyword",
            "meta": "keyword",
            "body": "keyword",
            "span": "keyword",
            "link": "keyword",
            "input": "keyword",
            "button": "keyword",
            "section": "keyword",
            "header": "keyword",
            "footer": "keyword",
            "script": "keyword",
            "style": "keyword",
            "table": "keyword",
            "title": "keyword",
            "blockquote": "keyword",
            "center": "keyword",
            "canvas": "keyword",
            "doctype": "keyword",
            "DOCTYPE": "keyword",
            "absolute": "argument",
            "all": "argument",
            "antialiased": "argument",
            "auto": "argument",
            "block": "argument",
            "bold": "argument",
            "border": "keyword",
            "bottom": "keyword",
            "box": "keyword",
            "column": "keyword",
            "default": "argument",
            "dotted": "argument",
            "drag": "argument",
            "ease": "argument",
            "ew": "argument",
            "fadein": "argument",
            "flex": "keyword",
            "forwards": "argument",
            "from": "argument",
            "grab": "argument",
            "grid": "keyword",
            "hidden": "argument",
            "in": "argument",
            "initial": "argument",
            "inline": "argument",
            "inset": "argument",
            "italic": "argument",
            "justify": "argument",
            "larger": "argument",
            "left": "keyword",
            "lr": "argument",
            "middle": "argument",
            "move": "argument",
            "no": "argument",
            "normal": "argument",
            "nowrap": "argument",
            "ns": "argument",
            "out": "argument",
            "pointer": "keyword",
            "relative": "argument",
            "repeat": "keyword",
            "resize": "keyword",
            "right": "keyword",
            "round": "argument",
            "row": "argument",
            "scalex": "argument",
            "scaley": "argument",
            "scroll": "argument",
            "smaller": "argument",
            "solid": "argument",
            "static": "argument",
            "text": "keyword",
            "to": "argument",
            "top": "keyword",
            "translate": "argument",
            "translate3d": "argument",
            "translatex": "argument",
            "translatey": "argument",
            "translatez": "argument",
            "transparent": "argument",
            "underline": "argument",
            "uppercase": "argument",
            "vertical": "keyword",
            "visible": "argument",
            "red": "property color",
            "green": "property color",
            "blue": "property color",
            "yellow": "property color",
            "magenta": "property color",
            "cyan": "property color",
            "black": "property color",
            "gray": "property color",
            "white": "keyword",
            "orange": "property color",
            "abs": "keyword",
            "after": "keyword",
            "align": "keyword",
            "animation": "keyword",
            "app": "keyword",
            "background": "keyword",
            "before": "keyword",
            "blend": "keyword",
            "caret": "keyword",
            "clip": "keyword",
            "color": "keyword",
            "content": "keyword",
            "corner": "keyword",
            "count": "keyword",
            "cursor": "keyword",
            "dasharray": "keyword",
            "dashoffset": "keyword",
            "decoration": "keyword",
            "delay": "keyword",
            "direction": "keyword",
            "display": "keyword",
            "duration": "keyword",
            "events": "keyword",
            "family": "keyword",
            "fill": "keyword",
            "filter": "keyword",
            "float": "keyword",
            "flow": "keyword",
            "font": "keyword",
            "function": "keyword",
            "grow": "keyword",
            "height": "keyword",
            "image": "keyword",
            "index": "keyword",
            "iteration": "keyword",
            "line": "keyword",
            "linecap": "keyword",
            "linejoin": "keyword",
            "list": "keyword",
            "margin": "keyword",
            "max": "keyword",
            "min": "keyword",
            "mode": "keyword",
            "opacity": "keyword",
            "origin": "keyword",
            "outline": "keyword",
            "overflow": "keyword",
            "padding": "keyword",
            "position": "keyword",
            "property": "keyword",
            "radius": "keyword",
            "region": "keyword",
            "scrollbar": "keyword",
            "select": "keyword",
            "selection": "keyword",
            "shadow": "function",
            "shrink": "keyword",
            "size": "keyword",
            "sizing": "keyword",
            "smoothing": "keyword",
            "space": "keyword",
            "start": "keyword",
            "stroke": "keyword",
            "thumb": "keyword",
            "timing": "keyword",
            "track": "keyword",
            "transform": "keyword",
            "transition": "keyword",
            "type": "keyword",
            "user": "keyword",
            "webkit": "keyword",
            "weight": "keyword",
            "width": "keyword",
            "word": "keyword",
            "writing": "keyword",
            "x": "keyword",
            "y": "keyword",
            "z": "keyword",
            "zoom": "keyword",
            "rgb": "function",
            "rgba": "function",
            "drop": "function",
            "linear": "function",
            "gradient": "function",
            "important": "important",
            "not": "property special",
            "hover": "property special",
            "focus": "property special",
            "active": "property special",
            "first": "property special",
            "last": "property special",
            "nth": "property special",
            "child": "property special",
            "none": "nil"
        },
        "scss": {
            "a": "keyword",
            "b": "keyword",
            "p": "keyword",
            "ul": "keyword",
            "li": "keyword",
            "br": "keyword",
            "tr": "keyword",
            "th": "keyword",
            "td": "keyword",
            "dt": "keyword",
            "hr": "keyword",
            "h1": "keyword",
            "h2": "keyword",
            "h3": "keyword",
            "h4": "keyword",
            "h5": "keyword",
            "div": "keyword",
            "nav": "keyword",
            "img": "keyword",
            "pre": "keyword",
            "map": "keyword",
            "area": "keyword",
            "html": "keyword",
            "head": "keyword",
            "meta": "keyword",
            "body": "keyword",
            "span": "keyword",
            "link": "keyword",
            "input": "keyword",
            "button": "keyword",
            "section": "keyword",
            "header": "keyword",
            "footer": "keyword",
            "script": "keyword",
            "style": "keyword",
            "table": "keyword",
            "title": "keyword",
            "blockquote": "keyword",
            "center": "keyword",
            "canvas": "keyword",
            "doctype": "keyword",
            "DOCTYPE": "keyword",
            "absolute": "argument",
            "all": "argument",
            "antialiased": "argument",
            "auto": "argument",
            "block": "argument",
            "bold": "argument",
            "border": "keyword",
            "bottom": "keyword",
            "box": "keyword",
            "column": "keyword",
            "default": "argument",
            "dotted": "argument",
            "drag": "argument",
            "ease": "argument",
            "ew": "argument",
            "fadein": "argument",
            "flex": "keyword",
            "forwards": "argument",
            "from": "argument",
            "grab": "argument",
            "grid": "keyword",
            "hidden": "argument",
            "in": "argument",
            "initial": "argument",
            "inline": "argument",
            "inset": "argument",
            "italic": "argument",
            "justify": "argument",
            "larger": "argument",
            "left": "keyword",
            "lr": "argument",
            "middle": "argument",
            "move": "argument",
            "no": "argument",
            "normal": "argument",
            "nowrap": "argument",
            "ns": "argument",
            "out": "argument",
            "pointer": "keyword",
            "relative": "argument",
            "repeat": "keyword",
            "resize": "keyword",
            "right": "keyword",
            "round": "argument",
            "row": "argument",
            "scalex": "argument",
            "scaley": "argument",
            "scroll": "argument",
            "smaller": "argument",
            "solid": "argument",
            "static": "argument",
            "text": "keyword",
            "to": "argument",
            "top": "keyword",
            "translate": "argument",
            "translate3d": "argument",
            "translatex": "argument",
            "translatey": "argument",
            "translatez": "argument",
            "transparent": "argument",
            "underline": "argument",
            "uppercase": "argument",
            "vertical": "keyword",
            "visible": "argument",
            "red": "property color",
            "green": "property color",
            "blue": "property color",
            "yellow": "property color",
            "magenta": "property color",
            "cyan": "property color",
            "black": "property color",
            "gray": "property color",
            "white": "keyword",
            "orange": "property color",
            "abs": "keyword",
            "after": "keyword",
            "align": "keyword",
            "animation": "keyword",
            "app": "keyword",
            "background": "keyword",
            "before": "keyword",
            "blend": "keyword",
            "caret": "keyword",
            "clip": "keyword",
            "color": "keyword",
            "content": "keyword",
            "corner": "keyword",
            "count": "keyword",
            "cursor": "keyword",
            "dasharray": "keyword",
            "dashoffset": "keyword",
            "decoration": "keyword",
            "delay": "keyword",
            "direction": "keyword",
            "display": "keyword",
            "duration": "keyword",
            "events": "keyword",
            "family": "keyword",
            "fill": "keyword",
            "filter": "keyword",
            "float": "keyword",
            "flow": "keyword",
            "font": "keyword",
            "function": "keyword",
            "grow": "keyword",
            "height": "keyword",
            "image": "keyword",
            "index": "keyword",
            "iteration": "keyword",
            "line": "keyword",
            "linecap": "keyword",
            "linejoin": "keyword",
            "list": "keyword",
            "margin": "keyword",
            "max": "keyword",
            "min": "keyword",
            "mode": "keyword",
            "opacity": "keyword",
            "origin": "keyword",
            "outline": "keyword",
            "overflow": "keyword",
            "padding": "keyword",
            "position": "keyword",
            "property": "keyword",
            "radius": "keyword",
            "region": "keyword",
            "scrollbar": "keyword",
            "select": "keyword",
            "selection": "keyword",
            "shadow": "function",
            "shrink": "keyword",
            "size": "keyword",
            "sizing": "keyword",
            "smoothing": "keyword",
            "space": "keyword",
            "start": "keyword",
            "stroke": "keyword",
            "thumb": "keyword",
            "timing": "keyword",
            "track": "keyword",
            "transform": "keyword",
            "transition": "keyword",
            "type": "keyword",
            "user": "keyword",
            "webkit": "keyword",
            "weight": "keyword",
            "width": "keyword",
            "word": "keyword",
            "writing": "keyword",
            "x": "keyword",
            "y": "keyword",
            "z": "keyword",
            "zoom": "keyword",
            "rgb": "function",
            "rgba": "function",
            "drop": "function",
            "linear": "function",
            "gradient": "function",
            "important": "important",
            "not": "property special",
            "hover": "property special",
            "focus": "property special",
            "active": "property special",
            "first": "property special",
            "last": "property special",
            "nth": "property special",
            "child": "property special",
            "none": "nil"
        },
        "sass": {
            "a": "keyword",
            "b": "keyword",
            "p": "keyword",
            "ul": "keyword",
            "li": "keyword",
            "br": "keyword",
            "tr": "keyword",
            "th": "keyword",
            "td": "keyword",
            "dt": "keyword",
            "hr": "keyword",
            "h1": "keyword",
            "h2": "keyword",
            "h3": "keyword",
            "h4": "keyword",
            "h5": "keyword",
            "div": "keyword",
            "nav": "keyword",
            "img": "keyword",
            "pre": "keyword",
            "map": "keyword",
            "area": "keyword",
            "html": "keyword",
            "head": "keyword",
            "meta": "keyword",
            "body": "keyword",
            "span": "keyword",
            "link": "keyword",
            "input": "keyword",
            "button": "keyword",
            "section": "keyword",
            "header": "keyword",
            "footer": "keyword",
            "script": "keyword",
            "style": "keyword",
            "table": "keyword",
            "title": "keyword",
            "blockquote": "keyword",
            "center": "keyword",
            "canvas": "keyword",
            "doctype": "keyword",
            "DOCTYPE": "keyword",
            "absolute": "argument",
            "all": "argument",
            "antialiased": "argument",
            "auto": "argument",
            "block": "argument",
            "bold": "argument",
            "border": "keyword",
            "bottom": "keyword",
            "box": "keyword",
            "column": "keyword",
            "default": "argument",
            "dotted": "argument",
            "drag": "argument",
            "ease": "argument",
            "ew": "argument",
            "fadein": "argument",
            "flex": "keyword",
            "forwards": "argument",
            "from": "argument",
            "grab": "argument",
            "grid": "keyword",
            "hidden": "argument",
            "in": "argument",
            "initial": "argument",
            "inline": "argument",
            "inset": "argument",
            "italic": "argument",
            "justify": "argument",
            "larger": "argument",
            "left": "keyword",
            "lr": "argument",
            "middle": "argument",
            "move": "argument",
            "no": "argument",
            "normal": "argument",
            "nowrap": "argument",
            "ns": "argument",
            "out": "argument",
            "pointer": "keyword",
            "relative": "argument",
            "repeat": "keyword",
            "resize": "keyword",
            "right": "keyword",
            "round": "argument",
            "row": "argument",
            "scalex": "argument",
            "scaley": "argument",
            "scroll": "argument",
            "smaller": "argument",
            "solid": "argument",
            "static": "argument",
            "text": "keyword",
            "to": "argument",
            "top": "keyword",
            "translate": "argument",
            "translate3d": "argument",
            "translatex": "argument",
            "translatey": "argument",
            "translatez": "argument",
            "transparent": "argument",
            "underline": "argument",
            "uppercase": "argument",
            "vertical": "keyword",
            "visible": "argument",
            "red": "property color",
            "green": "property color",
            "blue": "property color",
            "yellow": "property color",
            "magenta": "property color",
            "cyan": "property color",
            "black": "property color",
            "gray": "property color",
            "white": "keyword",
            "orange": "property color",
            "abs": "keyword",
            "after": "keyword",
            "align": "keyword",
            "animation": "keyword",
            "app": "keyword",
            "background": "keyword",
            "before": "keyword",
            "blend": "keyword",
            "caret": "keyword",
            "clip": "keyword",
            "color": "keyword",
            "content": "keyword",
            "corner": "keyword",
            "count": "keyword",
            "cursor": "keyword",
            "dasharray": "keyword",
            "dashoffset": "keyword",
            "decoration": "keyword",
            "delay": "keyword",
            "direction": "keyword",
            "display": "keyword",
            "duration": "keyword",
            "events": "keyword",
            "family": "keyword",
            "fill": "keyword",
            "filter": "keyword",
            "float": "keyword",
            "flow": "keyword",
            "font": "keyword",
            "function": "keyword",
            "grow": "keyword",
            "height": "keyword",
            "image": "keyword",
            "index": "keyword",
            "iteration": "keyword",
            "line": "keyword",
            "linecap": "keyword",
            "linejoin": "keyword",
            "list": "keyword",
            "margin": "keyword",
            "max": "keyword",
            "min": "keyword",
            "mode": "keyword",
            "opacity": "keyword",
            "origin": "keyword",
            "outline": "keyword",
            "overflow": "keyword",
            "padding": "keyword",
            "position": "keyword",
            "property": "keyword",
            "radius": "keyword",
            "region": "keyword",
            "scrollbar": "keyword",
            "select": "keyword",
            "selection": "keyword",
            "shadow": "function",
            "shrink": "keyword",
            "size": "keyword",
            "sizing": "keyword",
            "smoothing": "keyword",
            "space": "keyword",
            "start": "keyword",
            "stroke": "keyword",
            "thumb": "keyword",
            "timing": "keyword",
            "track": "keyword",
            "transform": "keyword",
            "transition": "keyword",
            "type": "keyword",
            "user": "keyword",
            "webkit": "keyword",
            "weight": "keyword",
            "width": "keyword",
            "word": "keyword",
            "writing": "keyword",
            "x": "keyword",
            "y": "keyword",
            "z": "keyword",
            "zoom": "keyword",
            "rgb": "function",
            "rgba": "function",
            "drop": "function",
            "linear": "function",
            "gradient": "function",
            "important": "important",
            "not": "property special",
            "hover": "property special",
            "focus": "property special",
            "active": "property special",
            "first": "property special",
            "last": "property special",
            "nth": "property special",
            "child": "property special",
            "none": "nil"
        },
        "svg": {
            "g": "keyword",
            "svg": "keyword",
            "path": "keyword",
            "rect": "keyword",
            "line": "keyword",
            "defs": "keyword",
            "text": "keyword",
            "title": "keyword",
            "tspan": "keyword",
            "circle": "keyword",
            "ellipse": "keyword",
            "polygon": "keyword",
            "polyline": "keyword",
            "pattern": "keyword",
            "filter": "keyword",
            "stop": "keyword",
            "radialgradient": "keyword",
            "lineargradient": "keyword",
            "id": "property",
            "type": "property",
            "href": "property",
            "src": "property",
            "rel": "property",
            "lang": "property",
            "class": "property",
            "name": "property",
            "width": "property",
            "height": "property",
            "media": "property",
            "style": "property",
            "value": "property",
            "shape": "property",
            "coords": "property",
            "content": "property",
            "charset": "property",
            "viewbox": "property",
            "tabindex": "property",
            "onmouseover": "property",
            "onmouseout": "property"
        },
        "plist": {
            "array": "keyword",
            "dict": "keyword",
            "key": "keyword",
            "string": "keyword",
            "plist": "keyword"
        },
        "py": {
            "class": "keyword",
            "else": "keyword",
            "try": "keyword",
            "except": "keyword",
            "print": "keyword",
            "pass": "keyword",
            "of": "keyword",
            "in": "keyword",
            "not": "keyword",
            "or": "keyword",
            "and": "keyword",
            "return": "keyword",
            "import": "keyword",
            "from": "keyword",
            "break": "keyword",
            "continue": "keyword",
            "global": "keyword",
            "range": "keyword",
            "len": "keyword",
            "def": "keyword",
            "if": "keyword",
            "elif": "keyword",
            "for": "keyword",
            "while": "keyword",
            "__init__": "keyword"
        },
        "sh": {
            "case": "keyword",
            "cat": "keyword",
            "cd": "keyword",
            "color-ls": "keyword",
            "colorcat": "keyword",
            "cp": "keyword",
            "dirname": "keyword",
            "do": "keyword",
            "done": "keyword",
            "echo": "keyword",
            "elif": "keyword",
            "else": "keyword",
            "esac": "keyword",
            "exit": "keyword",
            "fi": "keyword",
            "git": "keyword",
            "grep": "keyword",
            "head": "keyword",
            "if": "keyword",
            "in": "keyword",
            "konrad": "keyword",
            "krep": "keyword",
            "ls": "keyword",
            "mkdir": "keyword",
            "noon": "keyword",
            "npm": "keyword",
            "open": "keyword",
            "pwd": "keyword",
            "rm": "keyword",
            "sort": "keyword",
            "tail": "keyword",
            "then": "keyword",
            "while": "keyword",
            "getopts": "module"
        },
        "bash": {
            "case": "keyword",
            "cat": "keyword",
            "cd": "keyword",
            "color-ls": "keyword",
            "colorcat": "keyword",
            "cp": "keyword",
            "dirname": "keyword",
            "do": "keyword",
            "done": "keyword",
            "echo": "keyword",
            "elif": "keyword",
            "else": "keyword",
            "esac": "keyword",
            "exit": "keyword",
            "fi": "keyword",
            "git": "keyword",
            "grep": "keyword",
            "head": "keyword",
            "if": "keyword",
            "in": "keyword",
            "konrad": "keyword",
            "krep": "keyword",
            "ls": "keyword",
            "mkdir": "keyword",
            "noon": "keyword",
            "npm": "keyword",
            "open": "keyword",
            "pwd": "keyword",
            "rm": "keyword",
            "sort": "keyword",
            "tail": "keyword",
            "then": "keyword",
            "while": "keyword",
            "getopts": "module"
        },
        "fish": {
            "~": "keyword",
            "if": "keyword",
            "else": "keyword",
            "end": "keyword",
            "then": "keyword",
            "and": "keyword",
            "env": "keyword",
            "printf": "keyword",
            "echo": "keyword",
            "exit": "keyword",
            "while": "keyword",
            "case": "keyword",
            "for": "keyword",
            "in": "keyword",
            "set": "keyword",
            "pwd": "keyword",
            "alias": "keyword",
            "test": "keyword",
            "function": "keyword",
            "source": "keyword",
            "return": "keyword",
            "set_color": "keyword"
        },
        "iss": {
            "appid": "keyword",
            "appname": "keyword",
            "appversion": "keyword",
            "apppublisher": "keyword",
            "apppublisherurl": "keyword",
            "appsupporturl": "keyword",
            "appupdatesurl": "keyword",
            "defaultdirname": "keyword",
            "defaultgroupname": "keyword",
            "allownoicons": "keyword",
            "outputdir": "keyword",
            "outputbasefilename": "keyword",
            "setupiconfile": "keyword",
            "compression": "keyword",
            "solidcompression": "keyword",
            "wizardimagefile": "keyword",
            "wizardsmallimagefile": "keyword",
            "true": "keyword",
            "false": "nil"
        },
        "ini": {
            "true": "keyword",
            "false": "nil"
        }
    }
}