var toExport = {}
var _k_

var rgs

import util from "./util.js"
let ranges = util.ranges
let inc = util.inc
let lang = util.lang

lang('json')
toExport["json"] = function ()
{
    rgs = ranges(`{ "A Z": 1 }`)
    compare(inc(rgs,2,'"'),'punct dictionary')
    compare(inc(rgs,3,'A'),'dictionary key')
    compare(inc(rgs,5,'Z'),'dictionary key')
    compare(inc(rgs,6,'"'),'punct dictionary')
    compare(inc(rgs,7,':'),'punct dictionary')
    rgs = ranges('"a": "http://domain.com"')
    inc(rgs,6,'http','url p    ▸ rotocol')
    compare(inc(rgs,10,':'),'punct url')
    compare(inc(rgs,11,'/'),'punct url')
    compare(inc(rgs,12,'/'),'punct url')
    compare(inc(rgs,13,'domain'),'url domain')
    compare(inc(rgs,19,'.'),'punct url tld')
    compare(inc(rgs,20,'com'),'url tld')
    rgs = ranges('"http://domain.com/dir/page.html"')
    compare(inc(rgs,1,'http'),'url protocol')
    compare(inc(rgs,5,':'),'punct url')
    compare(inc(rgs,6,'/'),'punct url')
    compare(inc(rgs,7,'/'),'punct url')
    compare(inc(rgs,8,'domain'),'url domain')
    compare(inc(rgs,14,'.'),'punct url tld')
    compare(inc(rgs,15,'com'),'url tld')
    compare(inc(rgs,18,'/'),'punct dir')
    rgs = ranges('"file.coffee"')
    compare(inc(rgs,1,'file'),'coffee file')
    compare(inc(rgs,5,'.'),'punct coffee')
    compare(inc(rgs,6,'coffee'),'coffee ext')
    rgs = ranges('"/some/path"')
    compare(inc(rgs,2,'some'),'text dir')
    compare(inc(rgs,6,'/'),'punct dir')
    compare(inc(rgs,7,'path'),'text file')
    rgs = ranges('"/some\\path/file.txt:10"')
    compare(inc(rgs,0,'"'),'punct string double')
    compare(inc(rgs,1,'/'),'punct dir')
    compare(inc(rgs,2,'some'),'text dir')
    compare(inc(rgs,16,'.'),'punct txt')
    compare(inc(rgs,20,':'),'string double')
    compare(inc(rgs,23,'"'),'punct string double')
    rgs = ranges('"./node_modules/.bin/mocha"')
    compare(inc(rgs,1,'.'),'text dir')
    compare(inc(rgs,2,'/'),'punct dir')
    compare(inc(rgs,3,'node_modules'),'text dir')
    compare(inc(rgs,15,'/'),'punct dir')
    compare(inc(rgs,16,'.'),'text dir')
    compare(inc(rgs,17,'bin'),'text dir')
    compare(inc(rgs,20,'/'),'punct dir')
    compare(inc(rgs,21,'mocha'),'text file')
    rgs = ranges('"66.70.0"')
    compare(inc(rgs,1,"66"),'semver')
    compare(inc(rgs,3,"."),'punct semver')
    compare(inc(rgs,4,"70"),'semver')
    compare(inc(rgs,6,"."),'punct semver')
    compare(inc(rgs,7,"0"),'semver')
    rgs = ranges('"^0.7.1"')
    compare(inc(rgs,1,"^"),'punct semver')
    compare(inc(rgs,2,"0"),'semver')
    compare(inc(rgs,4,"7"),'semver')
    compare(inc(rgs,6,"1"),'semver')
    rgs = ranges('"^1.0.0-alpha.12"')
    compare(inc(rgs,2,"1"),'semver')
    compare(inc(rgs,4,"0"),'semver')
    compare(inc(rgs,6,"0"),'semver')
    rgs = ranges('">=6.7.8"')
    compare(inc(rgs,1,">"),'punct semver')
    compare(inc(rgs,2,"="),'punct semver')
    compare(inc(rgs,3,"6"),'semver')
    compare(inc(rgs,4,"."),'punct semver')
    compare(inc(rgs,5,"7"),'semver')
    compare(inc(rgs,6,"."),'punct semver')
    compare(inc(rgs,7,"8"),'semver')
}
toExport["json"]._section_ = true
toExport._test_ = true
export default toExport
